// <auto-generated />
using System;
using HukukBuroYonetimSistemi.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace HukukBuroYonetimSistemi.Migrations
{
    [DbContext(typeof(MahkemeDbContext))]
    partial class MahkemeDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.9")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("HukukBuroYonetimSistemi.Models.Domain.GorevAtamalar", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int?>("GorevAtamaId")
                        .HasColumnType("int");

                    b.Property<int?>("UserId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("GorevAtamalar");
                });

            modelBuilder.Entity("HukukBuroYonetimSistemi.Models.Domain.Mahkemeler", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Diger")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("DosyaNo")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("DurusmaTarihi")
                        .HasColumnType("datetime2");

                    b.Property<string>("GelenEvrakTuru")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("GelmeTarihi")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("Gorev")
                        .HasColumnType("datetime2");

                    b.Property<int?>("GorevAtamaId")
                        .HasColumnType("int");

                    b.Property<DateTime>("HedefSureSonGun")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("InsertDate")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<string>("IsTuru")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Mahkeme")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("TebligTarihi")
                        .HasColumnType("datetime2");

                    b.Property<string>("TebligTuru")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("UpdateDate")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("GorevAtamaId")
                        .IsUnique()
                        .HasFilter("[GorevAtamaId] IS NOT NULL");

                    b.ToTable("Mahkemeler");
                });

            modelBuilder.Entity("HukukBuroYonetimSistemi.Models.Domain.Users", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("GorevAtamaId")
                        .IsRequired()
                        .HasColumnType("int");

                    b.Property<DateTime>("InsertDate")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Statu")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("UpdateDate")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("GorevAtamaId");

                    b.ToTable("Users");
                });

            modelBuilder.Entity("HukukBuroYonetimSistemi.Models.Domain.GorevAtamalar", b =>
                {
                    b.HasOne("HukukBuroYonetimSistemi.Models.Domain.Users", "User")
                        .WithMany()
                        .HasForeignKey("UserId");

                    b.Navigation("User");
                });

            modelBuilder.Entity("HukukBuroYonetimSistemi.Models.Domain.Mahkemeler", b =>
                {
                    b.HasOne("HukukBuroYonetimSistemi.Models.Domain.GorevAtamalar", "GorevAtama")
                        .WithOne("GorevAtama")
                        .HasForeignKey("HukukBuroYonetimSistemi.Models.Domain.Mahkemeler", "GorevAtamaId");

                    b.Navigation("GorevAtama");
                });

            modelBuilder.Entity("HukukBuroYonetimSistemi.Models.Domain.Users", b =>
                {
                    b.HasOne("HukukBuroYonetimSistemi.Models.Domain.GorevAtamalar", "GorevAtama")
                        .WithMany()
                        .HasForeignKey("GorevAtamaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("GorevAtama");
                });

            modelBuilder.Entity("HukukBuroYonetimSistemi.Models.Domain.GorevAtamalar", b =>
                {
                    b.Navigation("GorevAtama")
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
